apiVersion: batch/v1
kind: Job
metadata:
  name: add-queues
  namespace: ibm-mq-ns
spec:
  template:
    spec:
      containers:
      - name: mq-admin
        image: icr.io/ibm-messaging/mq:9.3.2.0-r1
        command: ["/bin/bash", "-c"]
        args:
          - |
            ls -ali
            echo "DEFINE QLOCAL('NEW.QUEUE.1')" | runmqsc secureapphelm
        env:
        - name: LICENSE
          value: accept
        volumeMounts:
        - name: qm-volume
          mountPath: /mnt/mqm
      restartPolicy: Never
      volumes:
      - name: qm-volume
        persistentVolumeClaim:
          claimName: qm-secureapphelm-ibm-mq-0
